language: php

php:
  - 5.6
  - 7.0

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml

after_script: bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6558032d8feecaa6bf33
    on_success: change
    on_failure: always
    on_start: never
